"""Add CreditCard model

Revision ID: 6f2461c1a24d
Revises: 7d61945ceac3
Create Date: 2025-11-06 03:28:14.532462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2461c1a24d'
down_revision: Union[str, None] = '7d61945ceac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('card_network', sa.String(length=50), nullable=True),
    sa.Column('annual_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('foreign_transaction_fee', sa.Float(), nullable=True),
    sa.Column('rewards', sa.JSON(), nullable=False),
    sa.Column('welcome_bonus', sa.JSON(), nullable=True),
    sa.Column('insurance_benefits', sa.JSON(), nullable=True),
    sa.Column('other_perks', sa.JSON(), nullable=True),
    sa.Column('min_income', sa.Integer(), nullable=True),
    sa.Column('min_household_income', sa.Integer(), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_creditcard_active', 'credit_cards', ['is_active'], unique=False)
    op.create_index('idx_creditcard_issuer_product', 'credit_cards', ['issuer', 'product_name'], unique=True)
    op.create_index(op.f('ix_credit_cards_id'), 'credit_cards', ['id'], unique=False)
    op.create_index(op.f('ix_credit_cards_issuer'), 'credit_cards', ['issuer'], unique=False)
    op.alter_column('quotas', 'statements_parsed',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotas', 'statements_parsed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_credit_cards_issuer'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_id'), table_name='credit_cards')
    op.drop_index('idx_creditcard_issuer_product', table_name='credit_cards')
    op.drop_index('idx_creditcard_active', table_name='credit_cards')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
