"""Add statement-based quota tracking

Revision ID: 7d61945ceac3
Revises: ce28234e7e43
Create Date: 2025-11-06 03:13:28.460044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d61945ceac3'
down_revision: Union[str, None] = 'ce28234e7e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add statements_parsed with default 0
    op.add_column('quotas', sa.Column('statements_parsed', sa.Integer(), nullable=True))
    op.execute("UPDATE quotas SET statements_parsed = 0 WHERE statements_parsed IS NULL")
    op.alter_column('quotas', 'statements_parsed', nullable=False)
    
    # Add statements_limit with default based on tier (5 for analyst, 50 for optimizer, 999999 for autopilot)
    # First add as nullable
    op.add_column('quotas', sa.Column('statements_limit', sa.Integer(), nullable=True))
    # Set default based on user tier
    op.execute("""
        UPDATE quotas q
        SET statements_limit = CASE 
            WHEN u.tier = 'analyst' THEN 5
            WHEN u.tier = 'optimizer' THEN 50
            WHEN u.tier = 'autopilot' THEN 999999
            ELSE 5
        END
        FROM users u
        WHERE q.user_id = u.id
    """)
    # Now make it non-nullable
    op.alter_column('quotas', 'statements_limit', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotas', 'statements_limit')
    op.drop_column('quotas', 'statements_parsed')
    # ### end Alembic commands ###
