"""Add statement_id to transactions

Revision ID: ce28234e7e43
Revises: 7cfbda3a8a40
Create Date: 2025-11-06 03:10:03.279346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce28234e7e43'
down_revision: Union[str, None] = '7cfbda3a8a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('statement_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'statements', ['statement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_column('transactions', 'statement_id')
    # ### end Alembic commands ###
